### ISSUE TITLE
frames periodically become unsorted in arena since 10.1

### ISSUE THREAD

**Issue by cixel** [Verubato/frame-sort#10] opened 2023-05-09 21:47 UTC
I'm not sure what causes it, but frames become unsorted during some arena matches. It seems like it happens more often than not, but that could be observation bias. Haven't tried without other addons yet.

Here are my settings:
![image](https://github.com/Verubato/frame-sort/assets/3770250/84ad3d78-4cc5-4ec7-a158-4814f3631eb0)

**Comment by Verubato** [comment] 2023-05-10 01:52
Thanks for the bug report, I will look into it.

**Comment by cixel** [comment] 2023-05-10 04:31
Awesome, thanks! Let me know if there's any testing you'd like me to do.

**Comment by Verubato** [comment] 2023-05-11 06:42
Update: 

My current guess is that Blizzard are refreshing the party/raid frames during combat and FrameSort can't apply sorting/spacing until combat drops. In a BG this could easily happen if someone joins or leaves the BG during combat, but I'm unsure what event/condition is triggering it during arena as the group wouldn't change.

Trying to figure out if there is a way to prevent Blizzard from refreshing frames during combat (and instead wait until combat drops) which I have attempted but haven't managed to block all avenues.

Still investigating a solution.

**Comment by alalama** [comment] 2023-05-11 08:15
I can confirm the same issue.
I'll try to pay attention to the team composition, maybe some pets getting summoned/killed could trigger that but no idea really. Might not help with preventing the refresh but to better pinpoint it out.

Thanks for the great addon!

**Comment by SweepyBoop** [comment] 2023-05-13 04:51
Recent updates to CompactPartyFrame additionally subscribes to UNIT_PET.
So probably try add this to the combat block logic and see if it fixes the issue

**Comment by Verubato** [comment] 2023-05-13 05:41
> Recent updates to CompactPartyFrame additionally subscribes to UNIT_PET. So probably try add this to the combat block logic and see if it fixes the issue

Thanks for letting me know! I will try this.

**Comment by Verubato** [comment] 2023-05-13 11:15
Just released a new version with SweepyBoop's suggested fix and will see how it goes.

**Comment by Verubato** [comment] 2023-05-15 00:13
Update: confirmed two temporary workarounds for now, you can either:

- Disable "Display Pets" in the Blizzard raid frame settings (this setting doesn't even seem to work anyway).

or

- Use Traditional sorting method instead of Taintless.

Hoping to get Taintless mode stable again but not sure how yet.

**Comment by cixel** [comment] 2023-05-15 15:03
Sorry for the lack of movement here, I haven't been able to play much this weekend. I really appreciate the hard work you've put into figuring this out. I'll aim to test it a bit either today or tomorrow when I get a chance to PvP.

**Comment by Verubato** [comment] 2023-05-15 15:08
All good! No stress if you're unavailable/busy.

**Comment by cixel** [comment] 2023-05-15 17:13
Tried it out in a solo shuffle and some 2s. 

Had no issues, even with hunters on my team and pet frames enabled. Mind control also doesn't seem to cause problems. Glad you found a solution you're happy with that seems to work. I'll let you decide if this is enough confirmation to close out the issue.

Thanks for a super useful addon!

**Comment by Verubato** [comment] 2023-05-16 09:58
That's great news.

I've just tested it out in some 3s and it seems very solid now.

I'll wait a few days for any other news from the community and then close this off.

**Comment by Verubato** [comment] 2023-05-19 06:27
Seems to be fixed now, closing issue.

**Closed by Verubato** 2023-05-19 06:27 UTC
